### ISSUE TITLE
GetUrl does not exist after set $navigationGroup = 'Manage Account'

### ISSUE THREAD

**Issue by amaurycid** [webbingbrasil/filament-jetstream-theme#1]
Hello, Following directions to add links to user manage account menu, after setting $navigationGroup in  resource pages to 'Manage Account', it throws this error:
Method Illuminate\Support\Collection::getUrl does not exist.

**Comment by dmandrade** [comment]
Fixed in the latest version (1.1.1)

Now user menu use filament core feature, to register new items to the user menu, you should use a service provider:

```php
use Filament\Facades\Filament;
use Filament\Navigation\UserMenuItem;
 
Filament::serving(function () {
    Filament::registerUserMenuItems([
        UserMenuItem::make()
            ->label('Settings')
            ->url(route('filament.pages.settings'))
            ->icon('heroicon-s-cog'),
        // ...
    ]);
});
```

let me know if works
